#!/bin/bash


echo
echo 'BEGIN OF unshare commands'
echo

# Назначем адрес и поднимаем виртуальные интерфейсы
ip addr add 10.0.3.2/24 dev inet-un
ip link set inet-un up

# Поднимаем loopback
ip link set lo up

# Можно просмотреть, какие устройства в наличии
# ip addr show
# ip netns list

ping 10.0.3.1

echo
echo 'END OF unshare commands'
echo 'Enter to bash'
echo

bash -i
